-- MySQL Script generated by MySQL Workbench
-- Thu Apr 28 19:45:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema api-eujoguei
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema api-eujoguei
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `api-eujoguei` DEFAULT CHARACTER SET utf8 ;
USE `api-eujoguei` ;

-- -----------------------------------------------------
-- Table `api-eujoguei`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-eujoguei`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api-eujoguei`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-eujoguei`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `birthday` DATE NULL,
  `avatar` VARCHAR(45) NULL,
  `nickname` VARCHAR(45) NULL,
  `site` VARCHAR(45) NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`, `id_user`),
  UNIQUE INDEX `nikname_UNIQUE` (`nickname` ASC) VISIBLE,
  UNIQUE INDEX `site_UNIQUE` (`site` ASC) VISIBLE,
  INDEX `fk_perfil_users_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `api-eujoguei`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api-eujoguei`.`typy_phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-eujoguei`.`typy_phone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api-eujoguei`.`phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-eujoguei`.`phones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NULL,
  `id_type_phone` INT NOT NULL,
  `id_perfil` INT NOT NULL,
  PRIMARY KEY (`id`, `id_type_phone`, `id_perfil`),
  INDEX `fk_phones_typy_phone1_idx` (`id_type_phone` ASC) VISIBLE,
  INDEX `fk_phones_perfil1_idx` (`id_perfil` ASC) VISIBLE,
  CONSTRAINT `fk_phones_typy_phone1`
    FOREIGN KEY (`id_type_phone`)
    REFERENCES `api-eujoguei`.`typy_phone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phones_perfil1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `api-eujoguei`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api-eujoguei`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-eujoguei`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `api-eujoguei`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `api-eujoguei`.`users_roles` (
  `fk_users_id` INT NOT NULL,
  `fk_roles_id` INT NOT NULL,
  PRIMARY KEY (`fk_users_id`, `fk_roles_id`),
  INDEX `fk_users_has_roles_roles1_idx` (`fk_roles_id` ASC) VISIBLE,
  INDEX `fk_users_has_roles_users1_idx` (`fk_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_roles_users1`
    FOREIGN KEY (`fk_users_id`)
    REFERENCES `api-eujoguei`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_roles_roles1`
    FOREIGN KEY (`fk_roles_id`)
    REFERENCES `api-eujoguei`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
